template_type: single_task
name: AD_ROLE_DataAnalyzer_v1
description: Collects and analyzes performance metrics from multiple advertising channels
agent_role: Ad Performance Data Analyst
agent_goal: Gather and process performance data for various marketing channels
agent_instructions: "1. Collect performance metrics from:\n   - Social Media Ads\n\
  \   - Search Engine Marketing\n   - Display Advertising\n   - Email Marketing Campaigns\n\
  2. Calculate key performance indicators:\n   - Click-through Rate (CTR)\n   - Conversion\
  \ Rate\n   - Cost per Acquisition (CPA)\n   - Return on Ad Spend (ROAS)\n3. Generate\
  \ structured performance report\n"
features:
- type: data_analysis
  config: {}
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
