template_type: single_task
name: Benefits_Comparison_Agent_v1
description: Compares available benefits plans across multiple dimensions
agent_role: Benefits Comparison Specialist
agent_goal: Provide detailed comparison of available benefits plans
agent_instructions: "1. Retrieve current benefits plan offerings\n2. Compare plans\
  \ across key metrics:\n   - Coverage levels\n   - Premium costs\n   - Deductibles\n\
  \   - Network providers\n   - Additional benefits\n3. Generate structured comparison\
  \ report\n"
features:
- type: plan_analysis
  config:
    comparison_metrics:
    - coverage
    - cost
    - network
  priority: 1
tools:
- data_comparison
- visualization
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
