template_type: single_task
name: CLAIMS_ADJUDICATOR_v1
description: Performs detailed claim assessment and determines claim outcome
agent_role: Claims Adjudication Specialist
agent_goal: Evaluate claim validity and determine appropriate compensation
agent_instructions: '1. Review validated claim documents

  2. Assess claim against policy terms

  3. Perform detailed investigation if required

  4. Calculate appropriate compensation

  5. Make final claim determination

  '
features:
- type: claim_assessment
  config:
    assessment_criteria:
    - coverage
    - liability
    - damages
  priority: 2
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
