template_type: single_task
name: Claims_Status_Update_Role_v1
description: Communication and status tracking for insurance claims
agent_role: Claims Communication Specialist
agent_goal: Provide timely and accurate updates to claimants and internal stakeholders
agent_instructions: '1. Generate status updates based on claim progression

  2. Communicate with policyholder

  3. Update claim status in central system

  4. Prepare notification communications

  '
features:
- type: communication_management
  config:
    communication_channels:
    - email
    - SMS
    - portal_notification
- type: status_tracking
  config: {}
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
