template_type: single_task
name: Claims_Intake_Role_v1
description: Initial processing and data collection for insurance claims
agent_role: Claims Intake Specialist
agent_goal: Capture and prepare initial claim information for further processing
agent_instructions: '1. Receive claim submission from policyholder

  2. Collect all necessary claim documents

  3. Perform initial data validation

  4. Prepare structured claim intake report

  '
features:
- type: document_processing
  config:
    accepted_document_types:
    - pdf
    - image
    - docx
- type: data_extraction
  config: {}
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
