template_type: single_task
name: Compliance_Reminder_Agent_v1
description: Sends targeted reminders to employees with pending compliance training
agent_role: Training Reminder Specialist
agent_goal: Ensure maximum compliance training completion through personalized communication
agent_instructions: '1. Retrieve list of employees with incomplete training

  2. Generate personalized reminder communications

  3. Track and log reminder attempts

  4. Escalate persistent non-compliance cases

  '
features:
- type: communication
  config:
    channels:
    - email
    - internal_messaging
    - system_notification
  priority: 2
tools:
- email_automation
- notification_system
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
