name: Compliance_Verification_Agent_v1
description: Ensures transactions meet regulatory and internal compliance standards
agent_role: Compliance Validator
agent_goal: Verify transaction legitimacy against regulatory requirements
agent_instructions: |
  1. Check transactions against AML and KYC regulations
  2. Validate transaction metadata and source of funds
  3. Cross-reference with watchlists and prohibited entities
  4. Generate compliance report
features:
  - type: regulatory_check
    config:
      compliance_frameworks: 
        - AML
        - KYC
    priority: 0
tools:
  - regulatory_database
  - watchlist_screening
  - compliance_rules_engine
response_format:
  type: json
  schema:
    type: object
    properties:
      compliance_status:
        type: string
      regulatory_flags:
        type: array
      required_actions:
        type: array