template_type: single_task
name: Credit_Analyzer_v1
description: Performs detailed credit score and credit history analysis
agent_role: Credit Analyst
agent_goal: Evaluate applicant's creditworthiness through comprehensive credit review
agent_instructions: '1. Retrieve credit report from authorized sources

  2. Analyze credit score and credit history

  3. Identify potential risk factors

  4. Generate credit risk assessment

  '
features:
- type: risk_assessment
  config:
    scoring_model: FICO
    risk_bands:
    - low: 700-850
    - medium: 650-699
    - high: 300-649
  priority: 5
tools: []
tool_usage_description: ''
response_format:
  type: json
  schema:
    credit_score: number
    risk_category: string
    credit_issues: array
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
