template_type: single_task
name: Customer_Info_Collector_v1
description: Collects and validates customer information for insurance quoting
agent_role: Customer Information Gatherer
agent_goal: Comprehensively collect and validate customer demographic and risk-related
  details
agent_instructions: "1. Prompt customer for detailed personal information\n2. Verify\
  \ and validate provided information\n3. Collect:\n   - Age\n   - Occupation\n  \
  \ - Health history\n   - Lifestyle factors\n   - Property details\n   - Existing\
  \ insurance coverage\n4. Perform initial data quality checks\n"
features:
- type: data_collection
  config: {}
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
