template_type: single_task
name: CustomerFeedback_Summarizer_v1
description: Creates comprehensive and actionable summaries of customer feedback
agent_role: Insights Communicator
agent_goal: Transform complex feedback analysis into clear, actionable reports
agent_instructions: '1. Synthesize analytical insights

  2. Create executive-level summary

  3. Highlight key recommendations

  4. Prepare presentation-ready documentation

  '
features:
- type: reporting
  config:
    output_formats:
    - executive_summary
    - detailed_report
    - presentation_deck
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
