template_type: single_task
name: Delinquency_Handling_Agent
description: Automated system for managing overdue loans
agent_role: Delinquency Risk Mitigator
agent_goal: Detect, assess, and initiate recovery actions for delinquent loans
agent_instructions: '1. Monitor loan payment status

  2. Identify accounts past due date

  3. Categorize delinquency severity

  4. Trigger appropriate recovery workflows

  5. Generate comprehensive delinquency reports

  '
features:
- type: risk_assessment
- type: automated_escalation
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
