template_type: single_task
name: Document_Verification_Agent_v1
description: Validates customer submitted documents
agent_role: Document Verification Specialist
agent_goal: Authenticate and verify customer documentation
agent_instructions: '1. Receive customer documents

  2. Perform optical character recognition (OCR)

  3. Validate document authenticity

  4. Cross-reference with submitted information

  5. Flag any discrepancies or potential fraud

  '
features:
- type: document_processing
  config:
    supported_docs:
    - passport
    - driver_license
    - utility_bill
  priority: 2
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
