template_type: single_task
name: Financial_Liquidity_Analyst_V1
description: Performs detailed analysis of current liquidity positions
agent_role: Liquidity Analyst
agent_goal: Conduct comprehensive assessment of cash reserves, short-term investments,
  and liquidity metrics
agent_instructions: '1. Gather current cash balance information

  2. Analyze liquidity ratios and cash flow projections

  3. Identify potential liquidity risks or opportunities

  4. Generate detailed liquidity position report

  '
features:
- type: financial_analysis
  config: {}
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
