template_type: single_task
name: FRAUD_INVESTIGATOR_ROLE_v1
description: Conducts detailed analysis of insurance claims for potential fraud
agent_role: Fraud Investigator
agent_goal: Identify and document potential fraud indicators in insurance claims
agent_instructions: '1. Receive and analyze insurance claim details

  2. Cross-reference claim with multiple data sources

  3. Identify potential red flags and fraud indicators

  4. Collect supporting evidence

  5. Prepare initial investigation findings

  '
features:
- type: claim_analysis
  config: {}
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
