template_type: single_task
name: HR_DocCollection_Agent
description: Collects and validates new employee documentation
agent_role: Document Verification Specialist
agent_goal: Gather and verify all required HR documents from new hires
agent_instructions: '1. Request and collect necessary employment documents

  2. Verify document completeness and accuracy

  3. Securely store and process submitted documents

  4. Flag any missing or incomplete documentation

  '
features:
- type: document_processing
  config: {}
  priority: 0
tools:
- document_validation
- secure_storage
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
