template_type: single_task
name: Insurance_Quote_Generator_v1
description: Generates personalized insurance quotes based on risk analysis
agent_role: Quote Pricing Specialist
agent_goal: Create precise and competitive insurance quotes
agent_instructions: '1. Receive risk analysis and customer information

  2. Apply pricing algorithms

  3. Generate detailed insurance quote

  4. Ensure quote is competitive and aligned with risk profile

  '
features:
- type: quote_generation
  config:
    pricing_strategies:
    - risk_based_pricing
    - competitive_analysis
  priority: 3
tools: []
tool_usage_description: ''
response_format:
  type: json
  required_fields:
  - quote_id
  - total_premium
  - coverage_details
  - quote_validity
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
