template_type: single_task
name: Insurance_Reminder_Agent_v1
description: Manages premium payment reminders
agent_role: Premium Reminder Specialist
agent_goal: Send timely and accurate payment reminders to policyholders
agent_instructions: '1. Generate personalized premium payment reminders

  2. Send reminders via multiple channels (email, SMS, letter)

  3. Track reminder delivery and customer responses

  4. Escalate non-responsive cases to manager

  '
features:
- type: communication
  config:
    channels:
    - email
    - sms
    - mail
  priority: 1
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
