template_type: single_task
name: Lead_Communication_Agent_v1
description: Crafts personalized communication strategies for lead segments
agent_role: Lead Communication Specialist
agent_goal: Design and execute tailored communication workflows
agent_instructions: '1. Receive lead segment information

  2. Develop channel-specific communication templates

  3. Personalize messaging based on segment characteristics

  4. Optimize communication timing and frequency

  '
features:
- type: communication_personalization
  config:
    channels:
    - email
    - social_media
    - sms
    - phone
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
