template_type: single_task
name: Marketing_Performance_Optimizer
description: Analyzes campaign performance and generates optimization recommendations
agent_role: Marketing Performance Strategist
agent_goal: Provide data-driven insights for campaign targeting, creative, and budget
  optimization
agent_instructions: "1. Analyze collected performance data\n2. Identify key performance\
  \ indicators (KPIs)\n3. Assess:\n   - Audience targeting effectiveness\n   - Creative\
  \ performance\n   - Budget allocation and ROI\n4. Generate specific optimization\
  \ recommendations\n5. Provide confidence scores for recommendations\n"
features:
- type: performance_analysis
  config:
    metrics:
    - CTR
    - Conversion Rate
    - CPA
    - ROAS
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
