template_type: single_task
name: Marketing_Landing_Page_Optimizer_v1
description: Conducts A/B testing for landing page variations
agent_role: Conversion Rate Optimization Specialist
agent_goal: Maximize landing page performance through systematic testing
agent_instructions: '1. Receive landing page design variations

  2. Set up controlled A/B testing environment

  3. Track user interactions and conversion metrics

  4. Perform statistical analysis

  5. Provide recommendations for page optimization

  '
features:
- type: conversion_optimization
  config:
    metrics:
    - conversion_rate
    - bounce_rate
    - time_on_page
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
