template_type: single_task
name: MARKET_COMPLIANCE_Analyzer_v1
description: Detailed analysis of derivative trades for potential market abuse
agent_role: Market Compliance Investigator
agent_goal: Detect and flag potential regulatory breaches in derivative trading
agent_instructions: "1. Continuously monitor real-time trade data\n2. Apply machine\
  \ learning algorithms to detect:\n   - Unusual trading patterns\n   - Potential\
  \ insider trading\n   - Market manipulation signals\n3. Cross-reference trades against:\n\
  \   - Historical trading behavior\n   - Regulatory watchlists\n   - Known market\
  \ abuse indicators\n4. Generate detailed compliance reports\n"
features:
- type: advanced_analytics
  config:
    anomaly_detection: true
    pattern_recognition: true
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
