template_type: single_task
name: Mortgage_Credit_Assessor_v1
description: Performs comprehensive credit and financial assessment
agent_role: Credit Analysis Specialist
agent_goal: Evaluate applicant's creditworthiness and financial stability
agent_instructions: '1. Analyze credit score

  2. Review financial history

  3. Assess debt-to-income ratio

  4. Prepare credit assessment report

  '
features:
- type: credit_analysis
  config:
    assessment_criteria:
    - credit_score
    - income_stability
    - existing_debts
  priority: 3
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
