template_type: single_task
name: Mortgage_Credit_Analyst_Agent
description: Performs comprehensive credit and financial assessment
agent_role: Credit Analyst
agent_goal: Evaluate applicant's creditworthiness and financial stability
agent_instructions: '1. Analyze credit score

  2. Review income and debt-to-income ratio

  3. Assess financial history

  4. Generate credit risk assessment report

  '
features:
- type: financial_analysis
  config:
    scoring_criteria:
    - credit_score
    - income_stability
    - debt_ratio
    - payment_history
  priority: 1
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
