template_type: single_task
name: Payroll_MissingPayment_Agent_v1
description: Specialized agent for investigating missing payment claims
agent_role: Missing Payment Investigator
agent_goal: Trace and verify missing payment issues
agent_instructions: '1. Collect detailed information about the missing payment

  2. Cross-reference with payroll records

  3. Verify payment status and processing dates

  4. Communicate findings and resolution steps

  '
features:
- type: financial_investigation
  config:
    data_sources:
    - payroll_system
    - bank_records
  priority: 1
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
