template_type: single_task
name: Policy_Cancellation_Agent_v1
description: Processes policy cancellation requests
agent_role: Policy Cancellation Specialist
agent_goal: Handle policy cancellations efficiently and compliantly
agent_instructions: '1. Verify cancellation request authenticity

  2. Check policy cancellation eligibility

  3. Calculate pro-rata refunds

  4. Process cancellation

  5. Generate cancellation confirmation

  '
features:
- type: policy_termination
  config:
    min_notice_period_days: 7
  priority: 1
tools: []
tool_usage_description: ''
response_format:
  type: json
  schema:
    type: object
    properties:
      cancellation_status:
        type: string
      refund_amount:
        type: number
      effective_cancellation_date:
        type: string
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
