template_type: single_task
name: Retirement_Planning_Role_v1
description: Specialized agent for creating detailed retirement plans
agent_role: Retirement Planning Specialist
agent_goal: Develop comprehensive retirement strategy
agent_instructions: '1. Analyze current retirement savings and projected needs

  2. Calculate required savings rate

  3. Recommend retirement investment strategies

  4. Project retirement income and potential shortfalls

  5. Suggest tax-efficient retirement saving methods

  '
features:
- type: financial_modeling
  config:
    retirement_projection: true
    investment_analysis: true
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
  schema:
    retirement_age: number
    annual_retirement_income_needed: number
    savings_gap: number
    recommended_investment_strategy: object
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
