template_type: single_task
name: Retirement_Planning_Specialist_v1
description: Specialized agent for retirement goal planning and analysis
agent_role: Retirement Planning Specialist
agent_goal: Develop personalized retirement savings and investment strategy
agent_instructions: '1. Analyze current retirement savings

  2. Project future retirement needs

  3. Recommend optimal retirement investment vehicles

  4. Calculate retirement readiness score

  '
features:
- type: financial_analysis
  config:
    retirement_projection: true
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
  schema:
    retirement_recommendations:
      current_savings: number
      projected_needs: number
      recommended_annual_contribution: number
      investment_allocation: object
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
