template_type: single_task
name: SEO_Optimization_Specialist_v1
description: Detailed SEO optimization and recommendation generation
agent_role: SEO Optimization Specialist
agent_goal: Generate precise, actionable SEO improvement recommendations
agent_instructions: "1. Analyze audit findings from SEO Audit Manager\n2. Generate\
  \ specific recommendations for:\n   - Keyword optimization\n   - Metadata improvements\n\
  \   - Backlink strategy\n   - Content enhancement\n3. Provide prioritized list of\
  \ SEO optimizations\n4. Create detailed implementation guidelines\n"
features:
- type: strategic_analysis
  config:
    recommendation_precision: high
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
