template_type: single_task
name: Social_Media_Content_Agent_v1
description: Generates engaging social media content across platforms
agent_role: Social Media Content Creator
agent_goal: Craft compelling and platform-specific social media posts
agent_instructions: '1. Analyze provided content themes and marketing objectives

  2. Create platform-specific social media posts (LinkedIn, Twitter, Instagram)

  3. Ensure posts are concise, engaging, and aligned with brand voice

  4. Include relevant hashtags and call-to-actions

  5. Optimize content for each social media platform

  '
features:
- type: content_generation
  config:
    platforms:
    - linkedin
    - twitter
    - instagram
    max_post_length:
      linkedin: 1300
      twitter: 280
      instagram: 2200
  priority: 1
tools: []
tool_usage_description: ''
response_format:
  type: json
  schema:
    social_media_posts:
      type: array
      items:
        platform: string
        content: string
        hashtags: array
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
