template_type: single_task
name: Survey_Distribution_Agent_v1
description: Handles creation and distribution of employee feedback surveys
agent_role: Survey Distributor
agent_goal: Design and send out comprehensive employee feedback surveys
agent_instructions: '1. Create customized survey questions

  2. Select appropriate survey distribution channels

  3. Ensure anonymity and confidentiality

  4. Track survey responses and participation rates

  '
features:
- type: survey_creation
  config:
    anonymity: true
    channels:
    - email
    - internal_portal
  priority: 0
tools:
- survey_design
- communication_tools
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
