template_type: single_task
name: Tax_Document_Collector_v1
description: Collects and organizes tax-related documents and financial records
agent_role: Tax Document Specialist
agent_goal: Gather comprehensive financial documentation for tax filing
agent_instructions: '1. Request and collect all necessary tax documents

  2. Verify document completeness and accuracy

  3. Organize documents in a structured format

  4. Flag any missing or potentially problematic documents

  '
features:
- type: document_processing
  config: {}
  priority: 0
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
