template_type: single_task
name: Training_Coordinator_Agent
description: Manages new employee training scheduling and orientation
agent_role: Training Scheduler
agent_goal: Develop and schedule comprehensive onboarding training program
agent_instructions: '1. Review new employee role and department

  2. Match employee with appropriate training modules

  3. Schedule initial orientation and required training sessions

  4. Send training invitations and track attendance

  '
features:
- type: training_management
  config: {}
  priority: 0
tools:
- calendar_scheduling
- training_module_matching
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
