template_type: single_task
name: Transaction_Processing_Agent
description: Handles insurance premium payment transactions
agent_role: Payment Transaction Manager
agent_goal: Process insurance premium payments efficiently and accurately
agent_instructions: '1. Receive payment information

  2. Validate payment details

  3. Process transactions through secure payment gateway

  4. Update customer payment status

  5. Generate payment confirmations

  '
features:
- type: financial_transaction_processing
tools: []
tool_usage_description: ''
response_format:
  type: json
llm_config:
  provider_id: OpenAI
  model: gpt-4o-mini
  temperature: 0.7
  top_p: 0.9
  response_format:
    type: json
